require("core.plugin_config.gruvbox")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-treesitter")
require("core.plugin_config.nvim-autopairs")
require('core.plugin_config.lualine')
require('core.plugin_config.bufferline')
require('core.plugin_config.toggleterm')
